### PR TITLE
disable for large files until performance issues are addressed

### PR DESCRIPTION
**Pull request by tzachar**

### CODE REVIEW

**Comment by p00f** [comment]
There's a huge pr by kil0metres pending, I'll merge this after that

**Comment by p00f** [comment]
@kil0meters do i merge this before you're done?

**Comment by p00f** [comment]
Do you want me to merge this for now or are you working on that PR? @tzachar

**Comment by p00f** [comment]
I merged this, thank you very much!

**Comment by tzachar** [comment]
10x :)

**Pull request merged**
