### PR TITLE
fix completion-menu slowdown

### PR DESCRIPTION
**Pull request by sunjon**
fixes https://github.com/p00f/nvim-ts-rainbow/issues/5

### CODE REVIEW

**Comment by p00f** [comment]
thanks!!

**Comment by p00f** [comment]
@sunjon Now it doesn't update on every keystroke, even when the pum is not visible

**Comment by p00f** [comment]
https://user-images.githubusercontent.com/36493671/102649050-8c4dc300-418e-11eb-8559-b7dbe4e6b349.mp4

**Comment by sunjon** [comment]
I've submitted another PR that fixes this.

**Pull request merged**
