### PR TITLE
Make color_no respect syntax semantics

### PR DESCRIPTION
**Pull request by kil0meters**
The current implementation of the `color_no` function simply counts the number of parent nodes for a given paren. Although this does give a "rainbow" effect, it is a fundamentally flawed approach because a single semantic object can take an arbitrary amount of nodes to describe. This leads to various inconsistencies in the rainbow parenthesis across different languages.

#### Expected order

expected_order

#### Result

old_behavior

Notice how the struct, enum, function, and the function parameters all have different colors and the nested if and while statements don't seem to sensibly represent the rainbow order I set for my theme.

### New Behavior

I implemented the `@rainbow.level` query that allows us to whitelist nodes to count for `color_no` on a per-syntax basis. This allows us to achieve a significantly more consistent rainbow effect across different languages.

new_behavior

I created new queries for each of the currently supported syntaxes, but they have not been extensively tested so there are likely many errors that will need to be fixed. Regardless, the new implementations will still likely result in more pleasing highlighting than the existing one.

### CODE REVIEW

**Comment by p00f** [comment]
This is genius

**Comment by p00f** [comment]
It looks good on what I tested, we'll deal with problems case-by-case

Also, I couldn't get `; inherits` to work so thanks!

**Comment by p00f** [comment]
Does it make performance worse or is it just me? 

https://user-images.githubusercontent.com/36493671/114266360-916fa000-9a13-11eb-95fb-138299d0b2eb.mp4

https://user-images.githubusercontent.com/36493671/114266365-93d1fa00-9a13-11eb-8b2a-e53dbbcb6b17.mp4

**Comment by p00f** [comment]
The file is https://gist.githubusercontent.com/rodamaral/8e33e9abe1c2d43b96b1bd7f0eab6614/raw/dbfa583ca1925b622faf6ab96b8bc7515e2e3f15/test.tsx from #5

**Comment by p00f** [comment]
Why `ipairs` instead of `pairs`? Order doesn't matter here right

https://github.com/p00f/nvim-ts-rainbow/pull/25/files#diff-934641f2a5b83ec2d8767d4f5cb0b3fca94085a62bae6c97f065ed7ec1c3556dR54

**Comment by p00f** [comment]
Because of #26 and the aforementioned performance regression, I'll unmerge this PR, download its patchset and reapply it on a test branch (giving proper authorship to you ) after doing languagetree things (so that only changed nodes are processed ).

I hope this is fine

**Comment by kil0meters** [comment]
> Why ipairs instead of pairs? Order doesn't matter here right

No reason.

> Because of #26 and the aforementioned performance regression, I'll unmerge this PR, download its patchset and reapply it on a test branch (giving proper authorship to you ) after doing languagetree things (so that only changed nodes are processed ).

No problem. I there are likely going to be several problems with various language syntaxes need to get ironed out. That's the downside with this approach.

I believe we can set

```scheme
(_) @rainbow.level
```
Do get the previous behavior for a language.

FYI #26 can be fixed with.

```diff
diff --git a/queries/python/rainbow.scm b/queries/python/rainbow.scm
index 49b9b80..357c29e 100644
--- a/queries/python/rainbow.scm
+++ b/queries/python/rainbow.scm
@@ -12,4 +12,6 @@
   (while_statement)
   (if_statement)
   (call)
+  (list)
+  (dictionary)
 ] @rainbow.level
```

**Comment by kil0meters** [comment]
I investigated the performance regression and the culprit was `get_rainbow_levels`  making the program walk the entire tree twice.

Vim startup time opening a 3000 line yaml file:
```
nothing:
333.869  000.004: --- NVIM STARTED ---

p00f/nvim-ts-rainbow/master:
397.728  000.005: --- NVIM STARTED ---

kil0meters/nvim-ts-rainbow/HEAD~1:
640.669  000.004: --- NVIM STARTED ---

kil0meters/nvim-ts-rainbow/master:
485.317  000.004: --- NVIM STARTED ---
```

There is obviously going to have to be some level of performance regression since there's just more stuff happening, but this seems way more managable.

**Comment by p00f** [comment]
Startup time is not really a problem, lag/freeze during editing is

**Comment by kil0meters** [comment]
It should be representative since it's the same callbackfn, being used, no?

**Comment by p00f** [comment]
Yeah just saying. Also there's charlesmallah/lua-profiler

**Comment by p00f** [comment]
I tried out your fork now, it seems atleast as fast as (if not slightly more idk). Create another PR when you think you're done!

**Comment by p00f** [comment]
Can you also add `(anon_fn_lit)` to clojure?

**Comment by p00f** [comment]
Hey I'm reimplementing this now, I'll give you authorship

**Pull request merged**
