### PR TITLE
Add support for LaTeX

### PR DESCRIPTION
**Pull request by theHamsta**
Screenshot_20210405_113251

Should we guard the begin/end pairs behind an option? How is this handled for html tags?

### CODE REVIEW

**Comment by theHamsta** [comment]
image

There is clearly an advantage to see the matching pairs when you have an unformatted latex document.

**Comment by p00f** [comment]
There's currently no html (thanks for the reminder), and I don't have an opinion on guarding it behind a flag (I don't edit latex by hand). Do whatever feels correct

**Comment by theHamsta** [comment]
You can now configure the behavior
```
      rainbow = {
        enable = true,
        extended_mode = {
          latex = true
        },
      },
```
or for all languages
```
      rainbow = {
        enable = true,
        extended_mode = true,
      },
```

**Comment by theHamsta** [comment]
Mhhh, `#latex-extended-mode?` will only work when the top-level language is latex. Need to fix that

**Comment by p00f** [comment]
Can latex be inside something else? I always thought code was inside latex

**Comment by theHamsta** [comment]
For your plugin it's always correct since you are only doing `:iter_captures` for the root tree. But when you would have a you would need to register all `<language>-extended-rainbow-mode?` on startup.

You currently have no rainbox highlighting when you have JS in a HTML buffer or JS in Svelte buffer (even if HTML had captures)

**Comment by theHamsta** [comment]
This solution would always work. But you would have to maintain a list with languages that have extended queries.
https://github.com/theHamsta/nvim-ts-rainbow/blob/64d6df3974c4ffaf11e87701fb733270ec38440a/lua/rainbow/internal.lua#L77-L91

**Pull request merged**
