### PR TITLE
fix attempt #2

### PR DESCRIPTION
**Pull request by sunjon**
should be fixed properly now.

### CODE REVIEW

**Comment by p00f** [comment]
yep. thank you!

**Comment by sunjon** [comment]
There are still issues in general with the plugin checking far too aggressively. I'll try find time to look into it.

**Comment by p00f** [comment]
#5 has been reopened

**Comment by p00f** [comment]
maybe the mistake is assuming it returns 1?
> pumvisible()						*pumvisible()*
>		Returns non-zero when the popup menu is visible, zero
>		otherwise.  See |ins-completion-menu|.
>		This can be used to avoid some things that would remove the
>		popup menu.

**Comment by p00f** [comment]
Nah it still lags

**Pull request merged**
